import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider, createTheme } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import theme from "@/theme";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <ThemeProvider theme={theme}>
        <body >
          <AppRouterCacheProvider>
            {children}
            <link href="https://fonts.googleapis.com/css?family=Kanit" rel="stylesheet" />
          </AppRouterCacheProvider>
        </body>
      </ThemeProvider>
    </html>
  );
}
